name: Mail on Star

on:
  watch:
    types: [ started ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v1.3.0
      with:
        # SMTP server address
        server_address: smtp.gmail.com
        # SMTP server port
        server_port: 467
        # Authenticate as this user to SMTP server
        username: quadmx08
        # Authenticate with this password to SMTP server
        password: ${{ GMAIL_PASS }}
        # Subject of mail message
        subject: Your a star âœ¨
        # Body of mail message (might be a filename to read from)
        body: Someone just starred your mail-on-star repo
        # Recipients mail addresses (separated with comma)
        to: mail-on-star@waylonwalker.com
        # Full name of mail sender
        from: quadmx08@gmail.com
